// SPDX-License-Identifier: AGPL-3.0-only
/**
 * ABI for HippoxSwapRouterV1.
 */
export const hippoxSwapV1RouterAbi = [
    { type: "function", name: "factory", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
    { type: "function", name: "WETH", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
    {
        type: "function",
        name: "addLiquidity",
        stateMutability: "nonpayable",
        inputs: [
            { type: "address" },
            { type: "address" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "address" },
            { type: "uint256" },
        ],
        outputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }],
    },
    {
        type: "function",
        name: "addLiquidityWithHook",
        stateMutability: "nonpayable",
        inputs: [
            { type: "address" },
            { type: "address" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "address" },
            { type: "uint256" },
            { type: "address" },
        ],
        outputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }],
    },
    {
        type: "function",
        name: "removeLiquidity",
        stateMutability: "nonpayable",
        inputs: [
            { type: "address" },
            { type: "address" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "address" },
            { type: "uint256" },
        ],
        outputs: [{ type: "uint256" }, { type: "uint256" }],
    },
    {
        type: "function",
        name: "addLiquidityETH",
        stateMutability: "payable",
        inputs: [
            { type: "address" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "address" },
            { type: "uint256" },
        ],
        outputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }],
    },
    {
        type: "function",
        name: "addLiquidityETHWithHook",
        stateMutability: "payable",
        inputs: [
            { type: "address" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "address" },
            { type: "uint256" },
            { type: "address" },
        ],
        outputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }],
    },
    {
        type: "function",
        name: "removeLiquidityETH",
        stateMutability: "nonpayable",
        inputs: [
            { type: "address" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "uint256" },
            { type: "address" },
            { type: "uint256" },
        ],
        outputs: [{ type: "uint256" }, { type: "uint256" }],
    },
    {
        type: "function",
        name: "swapExactTokensForTokens",
        stateMutability: "nonpayable",
        inputs: [
            { type: "uint256" },
            { type: "uint256" },
            { type: "address[]" },
            { type: "address" },
            { type: "uint256" },
        ],
        outputs: [{ type: "uint256[]" }],
    },
    {
        type: "function",
        name: "swapTokensForExactTokens",
        stateMutability: "nonpayable",
        inputs: [
            { type: "uint256" },
            { type: "uint256" },
            { type: "address[]" },
            { type: "address" },
            { type: "uint256" },
        ],
        outputs: [{ type: "uint256[]" }],
    },
    {
        type: "function",
        name: "swapExactETHForTokens",
        stateMutability: "payable",
        inputs: [
            { type: "uint256" },
            { type: "address[]" },
            { type: "address" },
            { type: "uint256" },
        ],
        outputs: [{ type: "uint256[]" }],
    },
    {
        type: "function",
        name: "swapExactTokensForETH",
        stateMutability: "nonpayable",
        inputs: [
            { type: "uint256" },
            { type: "uint256" },
            { type: "address[]" },
            { type: "address" },
            { type: "uint256" },
        ],
        outputs: [{ type: "uint256[]" }],
    },
    {
        type: "function",
        name: "quote",
        stateMutability: "view",
        inputs: [{ type: "uint256" }, { type: "address[]" }],
        outputs: [{ type: "uint256[]" }],
    },
    {
        type: "function",
        name: "quoteBatch",
        stateMutability: "view",
        inputs: [{ type: "uint256[]" }, { type: "address[][]" }],
        outputs: [{ type: "uint256[][]" }],
    },
] as const;